version: "3.9"

services:
  db:
    image: postgres:15
    container_name: logiclike-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logiclike_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: .
    container_name: logiclike-server
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/logiclike_db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
